#pragma once
#ifndef _instabilityXiEq_Header
#define _instabilityXiEq_Header

/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpentnbLib: The Open Source CFD Toolbox
   \\    /   O peration     | Website:  https://opentnbLib.org
    \\  /    A nd           | Copyright (C) 2011-2019 OpentnbLib Foundation
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpentnbLib.

    OpentnbLib is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpentnbLib is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpentnbLib.  If not, see <http://www.gnu.org/licenses/>.

Class
    tnbLib::XiEqModels::instability

Description
    This is the equilibrium level of the flame wrinkling generated by
    instability. It is a constant (default 2.5). It is used in
    @link XiModel.H @endlink.

SourceFiles
    instability.C

\*---------------------------------------------------------------------------*/

#include <XiEqModel.hxx>

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace tnbLib
{
    namespace XiEqModels
    {

        /*---------------------------------------------------------------------------*\
                                  Class instability Declaration
        \*---------------------------------------------------------------------------*/

        class instability
            :
            public XiEqModel
        {
            // Private Data

                //- Equilibrium Xi due to instability only
            scalar XiEqIn;

            //- Equilibrium Xi model due to all other effects
            autoPtr<XiEqModel> XiEqModel_;


        public:

            //- Runtime type information
            TypeName("instability");


            // Constructors

                //- Construct from components
            instability
            (
                const dictionary& XiEqProperties,
                const psiuReactionThermo& thermo,
                const compressible::RASModel& turbulence,
                const volScalarField& Su
            );

            //- Disallow default bitwise copy construction
            instability(const instability&);


            //- Destructor
            virtual ~instability();


            // Member Functions

                //- Return the flame-wrinking XiEq
            virtual tmp<volScalarField> XiEq() const;

            //- Update properties from given dictionary
            virtual bool read(const dictionary& XiEqProperties);


            // Member Operators

                //- Disallow default bitwise assignment
            void operator=(const instability&) = delete;
        };


        // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

    } // End namespace XiEqModels
} // End namespace tnbLib

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif // !_instabilityXiEq_Header
