#pragma once
#ifndef _swirlFlowRateInletVelocityFvPatchVectorField_Header
#define _swirlFlowRateInletVelocityFvPatchVectorField_Header



#endif // !_swirlFlowRateInletVelocityFvPatchVectorField_Header
