!
!      $Revision$
!
!      "@(#)IBM Platform MPI  (05/03/2005) Linux IA32"
!

!
!     $Id$
!
!     Copyright (C) 1997 University of Chicago.
!     See COPYRIGHT notice in top-level directory.
!    Copyright Platform Computing Inc., an IBM company, 2012
!
!
!    user include file for Fortran MPI-IO programs
!
      INTEGER MPI_MODE_RDONLY, MPI_MODE_RDWR, MPI_MODE_WRONLY
      INTEGER MPI_MODE_DELETE_ON_CLOSE, MPI_MODE_UNIQUE_OPEN
      INTEGER MPI_MODE_CREATE, MPI_MODE_EXCL
      INTEGER MPI_MODE_APPEND, MPI_MODE_SEQUENTIAL
      PARAMETER (MPI_MODE_RDONLY=2, MPI_MODE_RDWR=8, MPI_MODE_WRONLY=4)
      PARAMETER (MPI_MODE_CREATE=1, MPI_MODE_DELETE_ON_CLOSE=16)
      PARAMETER (MPI_MODE_UNIQUE_OPEN=32, MPI_MODE_EXCL=64)
      PARAMETER (MPI_MODE_APPEND=128, MPI_MODE_SEQUENTIAL=256)
!
      INTEGER MPI_FILE_NULL
      PARAMETER (MPI_FILE_NULL=0)
!
!      INTEGER MPI_MAX_DATAREP_STRING
!      PARAMETER (MPI_MAX_DATAREP_STRING=127)
!
      INTEGER MPI_SEEK_SET, MPI_SEEK_CUR, MPI_SEEK_END
      PARAMETER (MPI_SEEK_SET=600, MPI_SEEK_CUR=602, MPI_SEEK_END=604)
!
      INTEGER MPIO_REQUEST_NULL
      PARAMETER (MPIO_REQUEST_NULL=0)
!
      integer*8 MPI_DISPLACEMENT_CURRENT
      PARAMETER (MPI_DISPLACEMENT_CURRENT=-54278278)
!
      INTEGER MPI_OFFSET_KIND
      PARAMETER (MPI_OFFSET_KIND=8)
!
      INTEGER MPI_ORDER_C, MPI_ORDER_FORTRAN
      PARAMETER (MPI_ORDER_C=56, MPI_ORDER_FORTRAN=57)
      INTEGER MPI_DISTRIBUTE_BLOCK, MPI_DISTRIBUTE_CYCLIC
      INTEGER MPI_DISTRIBUTE_NONE, MPI_DISTRIBUTE_DFLT_DARG
      PARAMETER (MPI_DISTRIBUTE_BLOCK=121, MPI_DISTRIBUTE_CYCLIC=122)
      PARAMETER (MPI_DISTRIBUTE_NONE=123)
      PARAMETER (MPI_DISTRIBUTE_DFLT_DARG=-49767)
!
! Predefined I/O error classes
!
       integer MPI_ERR_ACCESS, MPI_ERR_AMODE
       integer MPI_ERR_BAD_FILE, MPI_ERR_CONVERSION
       integer MPI_ERR_DUP_DATAREP, MPI_ERR_FILE
       integer MPI_ERR_FILE_EXISTS, MPI_ERR_FILE_IN_USE
       integer MPI_ERR_IO, MPI_ERR_NO_SPACE
       integer MPI_ERR_NO_SUCH_FILE, MPI_ERR_NOT_SAME
       integer MPI_ERR_QUOTA, MPI_ERR_READ_ONLY
       integer MPI_ERR_UNSUPPORTED_DATAREP
       integer MPI_ERR_UNSUPPORTED_OPERATION
       parameter (MPI_ERR_ACCESS=35)
       parameter (MPI_ERR_AMODE=36)
       parameter (MPI_ERR_BAD_FILE=37)
       parameter (MPI_ERR_CONVERSION=38)
       parameter (MPI_ERR_DUP_DATAREP=39)
       parameter (MPI_ERR_FILE=40)
       parameter (MPI_ERR_FILE_EXISTS=41)
       parameter (MPI_ERR_FILE_IN_USE=42)
       parameter (MPI_ERR_IO=43)
       parameter (MPI_ERR_NO_SPACE=44)
       parameter (MPI_ERR_NO_SUCH_FILE=45)
       parameter (MPI_ERR_NOT_SAME=46)
       parameter (MPI_ERR_QUOTA=47)
       parameter (MPI_ERR_READ_ONLY=48)
       parameter (MPI_ERR_UNSUPPORTED_DATAREP=49)
       parameter (MPI_ERR_UNSUPPORTED_OPERATION=50)
!
